apiVersion: v1
kind: Service

metadata:
  name: secure-stream-service

spec:
  selector:
    app: secure-stream-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer